// Carga completa de la base de datos oficial del Colegio Esteban Echeverría
const baseDatos = {
  "REMA 7°": [
    {"codigo": "CO VPR M 7 A", "alumno": "Amante, Shanti Maylen", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Anacondio, Matteo Dario", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Baamonde, Nael", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Bevilacqua, Nina", "curso": "7º A", "pago": "NO", "estado": "No Matricula / Baja", "turno": "Sin Asignar", "obs": "No continúa ya que prioriza otra propuesta"},
    {"codigo": "CO VPR M 7 A", "alumno": "Bonazzi, Dellfina Emma", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Bustamante, Mateo Nicolas", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Bustamante, Santino Tomas", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Cabello, Amparo", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Campos, Luana Nicole", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Cannetti, Francesco", "curso": "7º A", "pago": "NO", "estado": "No Matricula / Baja", "turno": "Sin Asignar", "obs": "No matricularé"},
    {"codigo": "CO VPR M 7 A", "alumno": "Correa, Faustino", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "De Marco, Juan Pedro", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Fandino, Martina", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Fernandez, Mia Valentina", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Gamarra, Bautista Yamil", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Gariboldi, Valentino", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "González, Francesca Antonella", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Grella, Lorenzo Jose", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Herrera, Juan Ignacio", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Ledo Diaz, Dante Nicolas", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Linares, Lautaro Mateo", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Lucas, Francisco Benjamin", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Maldonado, Dante Gabriel", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Mangas, Tomas Joaquin", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Montes de Oca, Valentina", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Moysan, Bianca Morena", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Olguin, Nicolas Santiago", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Pared, Lorenzo Daniel", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Paz, Santino Nicolas", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Pereyra, Felipe Agustin", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Pirez, Benjamin", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Ramirez, Thiago Aaron", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Restelli, Valentino Ciro", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Ruiz, Thiago Francisco", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Soria, Francisco Gabriel", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 A", "alumno": "Sosa, Valentina Jazmin", "curso": "7º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Agosti, Valentino", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Albarracin, Lautaro Agustin", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Antola, Joaquin", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Aramburu, Sofia Mailen", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Arias, Tiziano Nicolas", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Avendano, Felipe Tiziano", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Ayala, Francisco", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Balzi, Francesca Mia", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Barreto, Thiago Tomas", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Barrientos, Joaquin Ciro", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Bertello, Santino Tomas", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Betti, Benjamin Mateo", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Branca, Francesca Mia", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"},
    {"codigo": "CO VPR M 7 B", "alumno": "Briceno, Emma Valentina", "curso": "7º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matrícula contado Junio"}
  ],
  "REMA DE 1 A 4": [
    {"codigo": "CO VSE M 1 BEA", "alumno": "Alonso, Thiago", "curso": "1º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BEA", "alumno": "Amaya Chaparro, Ian Lucas", "curso": "1º Lab 1", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BCB", "alumno": "Cantatore Ruge, Antonella", "curso": "1º B", "pago": "NO", "estado": "Pendiente", "turno": "Tarde", "obs": "MOROSIDAD"},
    {"codigo": "CO VSE M 1 BEA", "alumno": "Aquieri, Luciano Ariel", "curso": "1º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BEA", "alumno": "Aragon, Santino", "curso": "1º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BEA", "alumno": "Arias, Jazmin Maria", "curso": "1º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BCB", "alumno": "Arriola, Tiziano", "curso": "1º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BEA", "alumno": "Avalos, Malena Sofia", "curso": "1º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BEA", "alumno": "Avendano, Felipe", "curso": "1º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BCB", "alumno": "Ayala, Bruno Gabriel", "curso": "1º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BEA", "alumno": "Baldomero, Juan Manuel", "curso": "1º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BEA", "alumno": "Barboza, Joaquin Nicolas", "curso": "1º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BCB", "alumno": "Benitez, Juan Ignacio", "curso": "1º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BCB", "alumno": "Benitez, Maria Lujan", "curso": "1º B", "pago": "NO", "estado": "No Matricula / Baja", "turno": "Sin Asignar", "obs": "Se traslada a otra institución"},
    {"codigo": "CO VSE M 1 BEA", "alumno": "Brizuela, Franco Exequiel", "curso": "1º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BEA", "alumno": "Brodsky, Noah", "curso": "1º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BCB", "alumno": "Bustos, Camila Jazmin", "curso": "1º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BEA", "alumno": "Cabrera, Thiago Tomas", "curso": "1º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BCB", "alumno": "Calderon, Luana Sofia", "curso": "1º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 1 BEA", "alumno": "Cano, Mateo Agustin", "curso": "1º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 2 BEA", "alumno": "De La Rosa, Santino", "curso": "2º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 2 BCB", "alumno": "Duran, Sofia Belen", "curso": "2º B", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 3 BEA", "alumno": "Escobar, Lautaro", "curso": "3º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"},
    {"codigo": "CO VSE M 4 BEA", "alumno": "Fernandez, Nicolas", "curso": "4º A", "pago": "SI", "estado": "Confirmado", "turno": "Mañana", "obs": "Matriculado"}
  ],
  "NUEVOS 20262027": [],
  "SINTESIS PRE PLANTA NOVIEMBRE": []
};
